### PR TITLE
Add GitHub workflows for building GoZen

### LINKED ISSUE #75: Build system
We need a build system which we can set the version correctly, compile to GDExtension for all operating systems, build all projects and bind them into OS specific bundles.

### PR DESCRIPTION
**Pull request by aappaapp**
This PR attempts to add the ability to compile the GDExtension using GitHub Actions, build the GoZen executable, and maybe set some version or something. (Still a WIP)

Closes #75

Progress:
- [x] Compile GDExtension (Linux)
- [ ] Compile GDExtension (Windows)
- [ ] Compile GDExtension (MacOS)
- [ ] Build GoZen (Linux)
- [ ] Build GoZen (Windows)
- [ ] Build GoZen (MacOS)

### CODE REVIEW

**Comment by aappaapp** [comment]
I don't wanna spam people's emails with "PR run failed" so I'm gonna close it for now.

**Comment by voylin** [comment]
> I don't wanna spam people's emails with "PR run failed" so I'm gonna close it for now.

Didn't actually get any email about PR run failed. I tested the latest build of the GDExtension and it worked.

(For testing inside of the Godot editor you need to specify it is a "debug" version even though it's a release version inside of the *.gdextension file)

**Comment by voylin** [comment]
In the middle of changing some stuff of the GDExtensions to make it easier to make multiple GDExtensions and to make the project structure a bit better. I'm polling about the build systems as well as I'm considering switching them to Python scripts instead of bash scripts. Switching to python could make them easier to work with.

**Comment by aappaapp** [comment]
> In the middle of changing some stuff of the GDExtensions to make it easier to make multiple GDExtensions and to make the project structure a bit better. I'm polling about the build systems as well as I'm considering switching them to Python scripts instead of bash scripts. Switching to python could make them easier to work with.

Then maybe I should open a new PR after you switched to Python?

**Comment by voylin** [comment]
The switching is almost complete, just struggling to get the FFmpeg compiling for windows working again. I'll try to finish it by today. You could maintain the same PR I think, just update your branch to the master after the changes have been made. I'll let you know once I'm done.

**Comment by voylin** [comment]
Updated the builder to python in the recent commit.

**Pull request closed without merging**
