### PR TITLE
Multi monitor related fixes

### PR DESCRIPTION
**Pull request by ManpreetSingh2004**
- (Windows only) Removes the ability to hide the window behind the taskbar or other panels without affecting the ability to drag between monitors. New behavior:

https://github.com/VoylinsGamedevJourney/GoZen/assets/63737630/814ec84e-7d7b-4901-aeaf-5e14a4015f42

- Fixes an issue which occurs when the monitor, originally positioned at coordinates (0, 0), is moved, causing a corresponding offset in the window's position after dragging (or resizing) it. See attachment: 

https://github.com/VoylinsGamedevJourney/GoZen/assets/63737630/7281f34c-8416-4f8e-b8c8-a5b900c20162

### CODE REVIEW

**Comment by voylin** [comment]
Looks good and would also work well on Linux normally. (Linux has many different desktop environments, but would be impossible to take them all into account :p)

**Comment by aappaapp** [comment]
I tested this on my Windows machine and it works :) good job

**Comment by voylin** [comment]
When you feel that the PR is ready to be merged you can change it from draft to an actual PR ;)

**Review by voylin — APPROVED** [review]
Thank you for your work on this 😊

**Pull request merged**
